### ISSUE TITLE
Does render svg instead of inline mermaid

### ISSUE THREAD

**Issue by maurerle** [zjffun/reveal.js-mermaid-plugin#6]
I would like to have mermaidjs rendered inline instead of as svg, so that links and so on are working too.

I am currently using pandoc with a custom template (adding a script at the top an `RevealMermaid` to the plugins), so that I can add the following in my pandoc markdown slides:

```
::: mermaid
<pre>
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
</pre>
:::
```

Here it is not that cool, that I need to add the pre tags too..
I would love to have mermaid integration in pandoc->revealjs but that does not seem easy.

Just opening this issue to keep track of it.

**Comment by zjffun** [comment]
Yes, this plugin relies on `<pre>` to make sure the mermaid code not be changed when formatting. It seems there are two ways to remove `<pre>`:
- Make sure codes not changed by transformer and update [here](https://github.com/zjffun/reveal.js-mermaid-plugin/blob/3da2a9350f8d83cbda448e0071b069ede5e560b7/plugin/mermaid/plugin.js#LL28C38-L28C38) to using `innerHTML` to get the mermaid code.
- Get codes in the transform stage and put them in a safe place, and take them out and call mermaid to display them when the page is rendered.

**Comment by zjffun** [comment]
I tested it again and found without pre tag is work fine. Is there any error message in your case?

Example: https://codepen.io/1010543618/pen/MWRvgzX

**Comment by maurerle** [comment]
When I have a markdown file with a slide like this:

```
# myslide

::: mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
:::
```
and run it with
`pandoc -d pandoc.yaml IK/ik.md`

I get this:

```
<section id="myslide"
class="title-slide slide level2">
<h2>Agent-based simulation approach</h2>
<div class="mermaid">
<p>graph TD;     A-->B;     A-->C;     B-->D;     C-->D;</p>
</div>
</section>
```

So this might as well be a pandoc issue.. :(

**Comment by zjffun** [comment]
Plain importing the `mermaid.min.js` is a good solution 👍🏻. I will add this to the document.

Copy code in [this example](https://codepen.io/1010543618/pen/poBrEGE) to html and open will work fine.
