### ISSUE TITLE
Mindmaps doesn't work?

### ISSUE THREAD

**Issue by hrauch** [zjffun/reveal.js-mermaid-plugin#7]
I tried to use mindmaps with this example:

```
     <div class="mermaid">
      %%{init: {'theme':'forest'}}%%
mindmap
  root((mindmap))
    Origins
      Long history
      ::icon(bi bi-book-half)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On effectiveness
      <br/>
      and features
      On Automatic creation
        Uses
            Creative techniques
            Strategic planning
            Argument mapping
    Tools
      Pen and paper
      Mermaid
    </div>

```

But I got the error: "No diagram type detected for text".

**Comment by zjffun** [comment]
Thanks for your feedback. We will implement this function later, currently we can use mindmap like https://codepen.io/1010543618/pen/KKrBrbX?editors=1000 .

**Comment by zjffun** [comment]
[v2.0.0](https://www.npmjs.com/package/reveal.js-mermaid-plugin/v/2.0.0) released to support mindmaps. 🎉
Example: https://zjffun.github.io/reveal.js-mermaid-plugin/#/10
